In [1]:
import numpy as np

In [2]:
#HOMEWORK-QUESTION-1-versi0n of numpy
np.__version__

'1.19.2'

In [3]:
import pandas as pd

In [4]:
#QUESTION-2-version of pandas

pd.__version__

'1.1.3'

In [5]:
data=pd.read_csv("Downloads/data.csv")

In [6]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [7]:
#QUESTION-3-average price of BMW cars

df=pd.DataFrame(data)
df
df[df['Make']=="BMW"].MSRP.mean()

61546.76347305389

In [8]:
#QUESTION-4-missing values in Engine HP after 2015
df1=df[df['Year']>=2015]
df1["Engine HP"].isnull().sum()


51

In [9]:
#QUESTION-5 - average Engine HP,using mean and fillna
mean_hp_before=df1["Engine HP"].mean()
print(round(mean_hp_before))




273


In [10]:
mean_hp_after=df1["Engine HP"].fillna(mean_hp_before).mean()
print(round(mean_hp_after))

273


In [11]:
#QUESTION-6
df3=df[["Make","Engine HP","Engine Cylinders","highway MPG"]]
df3

Make  Engine HP  Engine Cylinders  highway MPG
0          BMW      335.0               6.0           26
1          BMW      300.0               6.0           28
2          BMW      300.0               6.0           28
3          BMW      230.0               6.0           28
4          BMW      230.0               6.0           28
...        ...        ...               ...          ...
11909    Acura      300.0               6.0           23
11910    Acura      300.0               6.0           23
11911    Acura      300.0               6.0           23
11912    Acura      300.0               6.0           23
11913  Lincoln      221.0               6.0           26

[11914 rows x 4 columns]

In [12]:
df3=df3[df3["Make"]=="Rolls-Royce"]
df3

Make  Engine HP  Engine Cylinders  highway MPG
2921   Rolls-Royce      325.0               8.0           15
3505   Rolls-Royce      563.0              12.0           19
5275   Rolls-Royce      563.0              12.0           21
5276   Rolls-Royce      563.0              12.0           21
5277   Rolls-Royce      563.0              12.0           21
5278   Rolls-Royce      563.0              12.0           21
5279   Rolls-Royce      563.0              12.0           20
5280   Rolls-Royce      563.0              12.0           20
5281   Rolls-Royce      563.0              12.0           21
5282   Rolls-Royce      563.0              12.0           21
5283   Rolls-Royce      563.0              12.0           21
5284   Rolls-Royce      563.0              12.0           21
7443   Rolls-Royce      322.0              12.0           15
7444   Rolls-Royce      322.0              12.0           15
7553   Rolls-Royce      453.0              12.0           19
7554   Rolls-Royce      453.0              12.0           19
7555   Rolls-Royce      453.0              12.0           19
7556   Rolls-Royce      453.0              12.0           19
7557   Rolls-Royce      453.0              12.0           19
7558   Rolls-Royce      453.0              12.0           19
7559   Rolls-Royce      453.0              12.0           19
7560   Rolls-Royce      453.0              12.0           19
7561   Rolls-Royce      453.0              12.0           19
7562   Rolls-Royce      453.0              12.0           19
7563   Rolls-Royce      453.0              12.0           19
7564   Rolls-Royce      453.0              12.0           19
9431   Rolls-Royce      322.0              12.0           15
9432   Rolls-Royce      322.0              12.0           15
11448  Rolls-Royce      624.0              12.0           21
11449  Rolls-Royce      624.0              12.0           21
11450  Rolls-Royce      624.0              12.0           21

In [13]:
df3.drop(columns='Make',inplace=True)
df3

C:\Users\LENOVO\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [14]:
df3=df3.drop_duplicates()

In [15]:
df3

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [16]:
X=df3.to_numpy()
print(X)
print("dimension:",X.ndim)
print("shape:",X.shape)


[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]
dimension: 2
shape: (7, 3)


In [17]:
X=np.asmatrix(X)
X

matrix([[325.,   8.,  15.],
        [563.,  12.,  19.],
        [563.,  12.,  21.],
        [563.,  12.,  20.],
        [322.,  12.,  15.],
        [453.,  12.,  19.],
        [624.,  12.,  21.]])

In [18]:
XTX=(X.T).dot(X)
XTX


matrix([[1.754801e+06, 3.965600e+04, 6.519600e+04],
        [3.965600e+04, 9.280000e+02, 1.500000e+03],
        [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [19]:
XTXinv=np.linalg.inv(XTX)
print(XTXinv)


[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


In [20]:
XTXinv.sum()

0.032212320677486195

In [21]:
#QUESTION-7

In [25]:
y=np.array([1000,1100,900,1200,1000,850,1300])
y


array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [26]:
a=XTXinv.dot(X.T)
a

matrix([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
         -0.0023309 ,  0.00266407],
        [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
         -0.00609915, -0.02848958],
        [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
          0.07339609, -0.04480526]])

In [27]:

w=a.dot(y)
w

matrix([[ 0.19989598, 31.02612262, 31.65378877]])